services:
    proxy:
        restart: always
        depends_on:
            - frontend
            - backend
        build:
            dockerfile: Dockerfile.dev
            context: ./apps/nginx
        ports:
            - '3050:80'
    backend:
        build:
            context: ./apps/backend
            dockerfile: Dockerfile.dev
        depends_on:
            - mongo
        volumes:
            - ./apps/backend/:/usr/src/app
            - /usr/src/app/.pnpm-store
            - /usr/src/app/node_modules
        #command: pnpm start:docker
        environment:
            MONGO_DATABASE_URL2: mongodb://mongo:27017/api
            MONGO_DATABASE_URL: mongodb://mongoUser:hatatitla123*+465@mongo:27017/api
            TOKEN_KEY: e3c9cfe5c8c1ceab90b84e56f1ce8d8e0fcd9485
            PORT: 5000
    frontend:
        build:
            context: ./apps/frontend
            dockerfile: Dockerfile.dev
        volumes:
            - ./apps/frontend:/usr/src/app
            - /usr/src/app/node_modules        
    mongo:
        image: 'mongo'
        command: mongod --auth --logpath /dev/null
        restart: unless-stopped
        environment:
            - MONGO_INITDB_DATABASE=api
            - MONGO_INITDB_ROOT_USERNAME=mongoUser
            - MONGO_INITDB_ROOT_PASSWORD=hatatitla123*+465
        volumes:
            - ./volumes/backups:/backup:ro
            - ./volumes/backend:/data/db
            - ./apps/entry_point/api-mongo-init.js:/docker-entrypoint-initdb.d/api-mongo-init.js:ro
        ports:
            - '29029:27017'
