FROM node:20-alpine

RUN npm i -g pnpm

WORKDIR /usr/src/app

#COPY package.json  ./
COPY package.json  pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

# COPY package.json ./
# RUN pnpm install --no-frozen-lockfile

COPY . .

#EXPOSE 8080
CMD [ "pnpm", "run", "dev" ]

